// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';

export function CancelSession(arg1:string):Promise<void>;

export function ConnectMCP(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function CreateGitWorktree(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateProject(arg1:string,arg2:string):Promise<session.Project>;

export function CreateProjectFromDir(arg1:string):Promise<session.Project>;

export function CreateSession(arg1:string,arg2:string):Promise<session.Session>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetGitBranch(arg1:string):Promise<string>;

export function GetProjects():Promise<Array<session.Project>>;

export function GetRecentDirectories():Promise<Array<string>>;

export function GetSessionMessages(arg1:string):Promise<Array<session.Message>>;

export function GetSessions(arg1:string):Promise<Array<session.Session>>;

export function GetSettings():Promise<Record<string, any>>;

export function ListDirectory(arg1:string):Promise<Array<Record<string, any>>>;

export function OpenInEditor(arg1:string,arg2:string):Promise<void>;

export function PickDirectory():Promise<string>;

export function ReadFileContent(arg1:string):Promise<string>;

export function RemoveGitWorktree(arg1:string,arg2:string):Promise<void>;

export function RestoreFile(arg1:string,arg2:string):Promise<void>;

export function ResumeSession(arg1:string):Promise<void>;

export function SaveSettings(arg1:Record<string, any>):Promise<void>;

export function ScheduleRoutine(arg1:string,arg2:string):Promise<void>;

export function SetEnvironment(arg1:string,arg2:Record<string, any>):Promise<void>;

export function SnapshotFile(arg1:string):Promise<string>;

export function SpawnPTY(arg1:string,arg2:string):Promise<void>;

export function StartAgentLoop(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WritePTY(arg1:string,arg2:string):Promise<void>;
